### ISSUE TITLE
Investigate copyright and licensing

### ISSUE THREAD

**Issue by DeckOfPandas** [WDDCP/commcare-wddcp#1]
How to attribute appropriate copyright to Dimagi and allow WDDCP to retain copyright of material created arpund Dimagi's platform

**Comment by bsharif** [comment]
As I've noted in issue #6 the /home/ page is based on a Dimagi [repo ](https://github.com/dimagi/commcarehq-prelogin) that:
>Dimagi owns copyright over this repository and reserves all rights.

So we should create our own simple landing page at some point. I'll open that as a new issue. 

Open to ideas on how to appropriately attribute Dimagi for their code, and how we separate that from any code create for our own use.

**Comment by DeckOfPandas** [comment]
Merging with #11
