### ISSUE TITLE
Change default branch to wddcp

### ISSUE THREAD

**Issue by lamby** [WDDCP/commcare-wddcp#26]
Please consider changing the default branch to ``wddcp``. This will ensure that pull requests will, by default, be created/compared against the "development" branch.

**Comment by lamby** [comment]
(It was, of course, my bad for not checking the list of commits that would be changed with my PRs; sorry about that)

**Comment by DeckOfPandas** [comment]
Done

I originally made `dimagi` the default so it was easy to see how our project had diverged from [https://github.com/dimagi/commcare-hq](https://github.com/dimagi/commcare-hq), but I agree it's confusing, so you're the vote that's tipped me over!
