### ISSUE TITLE
Still using dimagi email addresses

### ISSUE THREAD

**Issue by emord** [WDDCP/commcare-wddcp#34]
@TheTincho Just a heads up that you're currently sending emails over to some dimagi addresses that are defined here https://github.com/WDDCP/commcare-wddcp/blob/wddcp/settings.py#L491-L509 (which is really our issue and we should remove them from the repository)

Looks like you're already familiar with commcare-developers user group. Best of luck setting up commcare!

**Comment by NightTsarina** [comment]
Hi Jonathan,

Thanks for the heads-up, I had no idea the app was sending emails to those addresses. I am still trying to figure out how to make emails work properly :-)

**Comment by NightTsarina** [comment]
Hi, @emord I am setting up a new instance and again I see tons of emails trying to go to dimagi.com. Could you tell me where all this is configured? It is not in settings.py or in localsettings.py

**Comment by NightTsarina** [comment]
Ugh, nevermind, now I see in your first comment you had already pointed this out..

**Comment by emord** [comment]
Hi @TheTincho I'm going to close this ticket as in the most recent versions of our code, this no longer exists. Perhaps you can rebase what you're working on with the upstream's master?

If you have any more questions I invite you to join our forum https://forum.dimagi.com/c/developers We monitor this forum to answer questions about setting up instances of commcare

**Comment by NightTsarina** [comment]
Uhm, are you sure about that? I am working with a checkout from a month ago, and the emails were still sent to dimagi.com

**Comment by emord** [comment]
https://github.com/dimagi/commcare-hq/commit/c8222c2700420c73ab7ae66ca8e9849df93f675c#diff-bdf3ecebd8379ca98cc89e545fc90899 from November changed all of these to `None` in the default settings file. If there are any more references to that, please feel free to let us know or submit a PR to remove them
