### ISSUE TITLE
Publishing apps is broken 

### ISSUE THREAD

**Issue by bsharif** [WDDCP/commcare-wddcp#8]
Trying to publish an app is currently broken. 

Error message is:
`Cannot Create Menus
Details: Unable to validate the forms due to a server error. Please try again later.`

This is found when viewing the app design page:
Applications > [application name] > Make New Version
![fireshot capture 1 - releases - untitled application - comm_ - http___ec2-35-177-33-162 eu-west-2](https://user-images.githubusercontent.com/7132252/27769040-152e5920-5f19-11e7-8408-e59960c43039.png)

Seems the error is linked to the Formplayer service not running. 
[Dev group thread](https://groups.google.com/d/msg/commcare-developers/qD8BC8jKjDw/TUhpibBnBwAJ)

[Another thread](https://groups.google.com/d/msg/commcare-developers/vpABXpTlb5I/xD0s1CnGBQAJ)

Formplayer repo is [here](https://github.com/dimagi/formplayer)

**Comment by DeckOfPandas** [comment]
I'm not sure about formplayer, but I think the forms are handled  via js in-browser and don't touch the backend (evidence includes no server chat on performing above actions).

Whatever I click actually, I get some UI error, but the console error is always the same. The (first) offending line of code is (highlighted):

![screen shot 2017-07-12 at 09 21 59](https://user-images.githubusercontent.com/2399432/28108506-a783db02-66e3-11e7-9649-8f91f9d2a35e.png)

CloudCare docs are here: http://commcare-hq.readthedocs.io/cloudcare.html
So I'm going to start there.

**Comment by DeckOfPandas** [comment]
Closing this to replace with formplayer service issue
