### ISSUE TITLE
App preview is broken

### ISSUE THREAD

**Issue by bsharif** [WDDCP/commcare-wddcp#9]
App preview is currently broken. 
Probably related to the formplayer service not running as in issue #8 
`Error saving!
× Unable to connect to form playing service. Please report an issue if you continue to see this message.`

Issue appears when trying to click 'Start' on an app preview window. 
![fireshot capture 2 - releases - test application - commcare_ - http___ec2-35-177-33-162 eu-west-2](https://user-images.githubusercontent.com/7132252/27769093-13eb67be-5f1a-11e7-94da-5aa168dcf2da.png)

If we get the [formplayer](https://github.com/dimagi/formplayer) service running then hopefully an easy fix

**Comment by DeckOfPandas** [comment]
Closing this to replace with formplayer service issue
